#!/usr/bin/env bash
# Fail if a commit range carries any Claude/AI footprint. Required check on
# agent PRs to public repos; strip-attribution should have removed everything
# this scans for.
#
# Usage: footprint-scan.sh <base-ref> [head-ref]
set -euo pipefail

BASE="${1:?usage: footprint-scan.sh <base-ref> [head-ref]}"
HEAD_REF="${2:-HEAD}"
# git log A..B is reachability (commits in B not in A) and stays correct even
# once A has moved on; git diff A..B is a raw tree comparison with no
# ancestry, so it must be three-dot (against merge-base) or a base that has
# advanced since the branch forked makes every file base touched read as
# "touched by this branch" too (same bug as expertise-path-guard.sh, found
# live via a sandbox-verification PR).
RANGE="$BASE..$HEAD_REF"
DIFF_RANGE="$BASE...$HEAD_REF"
MARKERS='claude|anthropic'
FAILED=0

fail() { echo "FOOTPRINT: $1"; FAILED=1; }

# 1. Author/committer identity
while IFS=$'\t' read -r sha an ae cn ce; do
  if echo "$an $ae $cn $ce" | grep -qiE "$MARKERS"; then
    fail "commit $sha has Claude/Anthropic identity: $an <$ae> / $cn <$ce>"
  fi
done < <(git log --format=$'%h\t%an\t%ae\t%cn\t%ce' "$RANGE")

# 2. Commit messages
while read -r sha; do
  if git log -1 --format='%B' "$sha" | grep -qiE "(co-authored-by|generated with|generated by).*($MARKERS)|claude\.com|anthropic\.com|🤖"; then
    fail "commit $sha message contains attribution marker"
  fi
done < <(git log --format='%h' "$RANGE")

# 3. Config files that must never land in public repos
while read -r f; do
  case "$f" in
    CLAUDE.md|*/CLAUDE.md|.claude/*|*/.claude/*|.claude.json|*/.claude.json)
      fail "file '$f' is Claude configuration" ;;
  esac
done < <(git diff --name-only --diff-filter=ACMR "$DIFF_RANGE")

# 4. Added lines carrying attribution strings
if git diff "$DIFF_RANGE" | grep -E '^\+' | grep -qiE "(co-authored-by|generated (with|by)).*($MARKERS)|claude\.com/claude-code"; then
  fail "diff adds attribution string(s):"
  git diff "$DIFF_RANGE" | grep -E '^\+' | grep -iE "(co-authored-by|generated (with|by)).*($MARKERS)|claude\.com/claude-code" | head -5
fi

if [ "$FAILED" -ne 0 ]; then
  echo ""
  echo "Footprint scan FAILED. Run the strip-attribution action before pushing to public repos."
  exit 1
fi
echo "Footprint scan clean: $RANGE"
